### ISSUE TITLE
[BUG]: Doesn't compile after the latest 2025.12.0 update.

### ISSUE THREAD

**Issue by Opontios** [alaltitov/display#54]
### ✅ Prerequisites

- [x] I have checked that the problem is not related to incorrect entity configuration in Home Assistant
- [x] I have checked that the problem is not related to incorrect entity configuration in ESPHome
- [x] I have confirmed this is actually a bug, not a question (use Discussions for questions)

### 🔧 ESPHome Version

2025.12.0

### 📝 Bug Description

Can't compile the firmware.

### 📋 Error Logs

```shell
Compiling .pioenvs/display01/heap/port/memory_layout_utils.c.o /config/esphome/widgets/home/home.yaml: In lambda function: /config/esphome/widgets/home/home.yaml:2023:29: error: 'FontEngine' in namespace 'esphome::lvgl' does not name a type 2023 |           static esphome::lvgl::FontEngine fe_nunito_16(id(nunito_16)); |                             ^~~~~~~~~~ /config/esphome/widgets/home/home.yaml:2088:49: error: 'fe_nunito_16' was not declared in this scope; did you mean 'nunito_16'? 2088 |               lv_obj_set_style_text_font(day_label, fe_nunito_16.get_lv_font(), 0); |                                                 ^~~~~~~~~~~~ |                                                 nunito_16 /config/esphome/widgets/home/home.yaml:2106:50: error: 'fe_nunito_16' was not declared in this scope; did you mean 'nunito_16'? 2106 |               lv_obj_set_style_text_font(temp_label, fe_nunito_16.get_lv_font(), 0); |                                                  ^~~~~~~~~~~~ |                                                  nunito_16 /config/esphome/widgets/home/home.yaml: In lambda function: /config/esphome/widgets/home/home.yaml:2121:29: error: 'FontEngine' in namespace 'esphome::lvgl' does not name a type 2121 |           static esphome::lvgl::FontEngine fe_nunito_16(id(nunito_16)); |                             ^~~~~~~~~~ Compiling .pioenvs/display01/heap/port/esp32s3/memory_layout.c.o /config/esphome/widgets/home/home.yaml:2204:50: error: 'fe_nunito_16' was not declared in this scope; did you mean 'nunito_16'? 2204 |               lv_obj_set_style_text_font(time_label, fe_nunito_16.get_lv_font(), 0); |                                                  ^~~~~~~~~~~~ |                                                  nunito_16 Compiling .pioenvs/display01/http_parser/http_parser.c.o /config/esphome/widgets/home/home.yaml:2222:50: error: 'fe_nunito_16' was not declared in this scope; did you mean 'nunito_16'? 2222 |               lv_obj_set_style_text_font(temp_label, fe_nunito_16.get_lv_font(), 0); |                                                  ^~~~~~~~~~~~ |                                                  nunito_16 Compiling .pioenvs/display01/json/cJSON/cJSON.c.o Archiving .pioenvs/display01/esp-idf/heap/libheap.a Compiling .pioenvs/display01/json/cJSON/cJSON_Utils.c.o /config/esphome/widgets/climate/climate.yaml: In lambda function: /config/esphome/widgets/climate/climate.yaml:3681:29: error: 'FontEngine' in namespace 'esphome::lvgl' does not name a type 3681 |           static esphome::lvgl::FontEngine fe_mdi_24(id(mdi_icons_24)); |                             ^~~~~~~~~~ /config/esphome/widgets/climate/climate.yaml:3682:29: error: 'FontEngine' in namespace 'esphome::lvgl' does not name a type 3682 |           static esphome::lvgl::FontEngine fe_nunito_16(id(nunito_16)); |                             ^~~~~~~~~~ Compiling .pioenvs/display01/log/src/os/log_timestamp.c.o /config/esphome/widgets/climate/climate.yaml:3741:42: error: 'fe_mdi_24' was not declared in this scope 3741 |             lv_obj_set_style_text_font(icon, fe_mdi_24.get_lv_font(), 0); |                                          ^~~~~~~~~ /config/esphome/widgets/climate/climate.yaml:3748:41: error: 'fe_nunito_16' was not declared in this scope; did you mean 'nunito_16'? 3748 |             lv_obj_set_style_text_font(txt, fe_nunito_16.get_lv_font(), 0); |                                         ^~~~~~~~~~~~ |                                         nunito_16 /config/esphome/widgets/climate/climate.yaml: In lambda function: /config/esphome/widgets/climate/climate.yaml:3861:29: error: 'FontEngine' in namespace 'esphome::lvgl' does not name a type 3861 |           static esphome::lvgl::FontEngine fe_mdi_24(id(mdi_icons_24)); |                             ^~~~~~~~~~ /config/esphome/widgets/climate/climate.yaml:3862:29: error: 'FontEngine' in namespace 'esphome::lvgl' does not name a type 3862 |           static esphome::lvgl::FontEngine fe_nunito_16(id(nunito_16)); |                             ^~~~~~~~~~ /config/esphome/widgets/climate/climate.yaml:3918:42: error: 'fe_mdi_24' was not declared in this scope 3918 |             lv_obj_set_style_text_font(icon, fe_mdi_24.get_lv_font(), 0); |                                          ^~~~~~~~~ /config/esphome/widgets/climate/climate.yaml:3925:41: error: 'fe_nunito_16' was not declared in this scope; did you mean 'nunito_16'? 3925 |             lv_obj_set_style_text_font(txt, fe_nunito_16.get_lv_font(), 0); |                                         ^~~~~~~~~~~~ |                                         nunito_16 Compiling .pioenvs/display01/log/src/log_timestamp_common.c.o /config/esphome/widgets/media_player/media_player.yaml: In lambda function: /config/esphome/widgets/media_player/media_player.yaml:926:29: error: 'FontEngine' in namespace 'esphome::lvgl' does not name a type 926 |           static esphome::lvgl::FontEngine fe_nunito_16(id(nunito_16)); |                             ^~~~~~~~~~ /config/esphome/widgets/media_player/media_player.yaml:980:41: error: 'fe_nunito_16' was not declared in this scope; did you mean 'nunito_16'? 980 |             lv_obj_set_style_text_font(txt, fe_nunito_16.get_lv_font(), 0); |                                         ^~~~~~~~~~~~ |                                         nunito_16 Archiving .pioenvs/display01/esp-idf/json/libjson.a
```

### ⚙️ Configuration

```yaml

```

**Comment by alaltitov** [comment]
It won't work on 2025.12.0 because the API has changed.

**Comment by Opontios** [comment]
What should I be doing next?

**Comment by alaltitov** [comment]
@Opontios 
Nothing, install 2025.11.5. As I already asked you in the discussions, I'll repeat myself: why do you need version 2025.12.0? Especially for this device, for which the latest version breaks everything... There's no point in fixing it for every version, considering that LVGL 9.4 is currently being implemented, and you'll have to fix it again in a week. Just accept this as a fact: don't update as soon as a new version is released! Why? Here are some options:
1) It could easily break everything.
2) The latest version could be unstable, especially in an open source project like Home Assistant or ESPHome.
3) There's no point in updating if it doesn't have critical features for you.

P.S. And please, a big request:
1) Write in English (even with a translator), as people from all over the world read this.
2) Don't open an issue if it's related to the ESPHome version! As they're constantly changing things there. There was a case where someone installed the DEV!!! version of ESPHome and couldn't figure out why it wouldn't launch! I can't edit the project for every new version of ESPHome; I simply don't have the time; I have other projects.
3) After the New Year holidays, I'll make the code working for the latest (at that time) version, when the stable version of the LVGL component is released in version 9.4 for ESPHome.

P.P.S. But perhaps it's not so obvious for ordinary users, and it's worth adding in the README.md that it works on versions 2025.11.0 > <2025.12.0

**Comment by Opontios** [comment]
Thanks a lot for a fast response and all your explanations. I'll try to keep in mind everything. Writing in English is not an issue at all. I guess I was just influenced from other users I saw in discussions that were writing in Russian. 
I'm updating all my ESPHome devices with the latest versions more because of a habit to have it all up to date. But you're totally right, in case of the display it's not necessary at all, so I'll stick to your advice. 
Thanks again.

**Comment by alaltitov** [comment]
@Opontios  Yep, you got it right! But, unfortunately, a new version ≠ the current version. Or rather, of course, it adds new features (which, by the way, you don't always need; see the [changelog](https://esphome.io/changelog/2025.12.0/)), and, as a rule, the latest versions are patched very frequently. Therefore, it's best to update not immediately, but after a few versions, if you really need the features you need. Let me put it this way: in ESPHome, it's far from guaranteed that a new version will make your devices more stable. Some devices ONLY work with older versions, even those from six months ago. It would be quite difficult and time-consuming for me to explain how this works, but trust me. I understand how users see it: if it's new, it means it's better! But, unfortunately, that's not the case.

P.S. If you want quick answers to your questions, it's easier for you to join the Telegram [group](https://t.me/esphome_lvgl_chats)... Yes, there are almost no discussions there, but you can always get a quick answer from me in your native language. News on all my projects appears faster there. It's also much easier for me to explain some of the nuances there. With your permission, I'll close this issue tomorrow. Have a nice day.

**Comment by AlienKnalKoe** [comment]
Remove the two static esphome::lvgl::FontEngine ... lines entirely from both scripts.
replace the other 'fe_mdi_24' and 'fe_nunito_16' in home and climate.yaml into
lv_obj_set_style_text_font(icon, id(mdi_icons_24), 0);
lv_obj_set_style_text_font(txt, id(nunito_16), 0);

Its working again !!

**Comment by CodeFinder2** [comment]
> Remove the two static esphome::lvgl::FontEngine ... lines entirely from both scripts. replace the other 'fe_mdi_24' and 'fe_nunito_16' in home and climate.yaml into lv_obj_set_style_text_font(icon, id(mdi_icons_24), 0); lv_obj_set_style_text_font(txt, id(nunito_16), 0);
> 
> Its working again !!

Verified to be also compatible with ESPHome v2026.1.0 after applying the quoted fixes.

**Comment by janosch1337** [comment]
for me its not working. can someone post his home.yaml + climate.yaml?

**Comment by alaltitov** [comment]
@janosch1337 https://github.com/alaltitov/Guition-ESP32-S3-4848S040/tree/2026.1.4
